version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: parceler_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-networklogging:
  driver: json-file
  options:
    labels: "service"
    env: "os,customer"
    compress: "true"
    max-size: "10m"
    max-file: "3"

volumes:
  postgres_data:

networks:
  my-network:
